### ISSUE TITLE
Build issue (Fallback bindings does not support this interface yet)

### ISSUE THREAD

**Issue by FredrikNoren** [Menci/vite-plugin-top-level-await#43]
Same as #17 

I'm trying to get things to build on github actions.

It all works locally (i.e. `npm run build` works), but this is the output I'm getting on github actions:

```
vite v5.0.12 building for production...
transforming...
✓ 1256 modules transformed.
[vite:worker] Fallback bindings does not support this interface yet.
file: /home/runner/work/Prompty/Prompty/web_next/src/worker.ts?worker&url
error during build:
Error: Fallback bindings does not support this interface yet.
    at Compiler.<anonymous> (/home/runner/work/Prompty/Prompty/web_next/node_modules/@swc/core/index.js:122:23)
    at Generator.next (<anonymous>)
    at /home/runner/work/Prompty/Prompty/web_next/node_modules/@swc/core/index.js:34:71
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/work/Prompty/Prompty/web_next/node_modules/@swc/core/index.js:30:12)
    at Compiler.parse (/home/runner/work/Prompty/Prompty/web_next/node_modules/@swc/core/index.js:[118](https://github.com/AmbientRun/Prompty/actions/runs/7785677277/job/21228813230#step:6:119):16)
    at Object.parse (/home/runner/work/Prompty/Prompty/web_next/node_modules/@swc/core/index.js:323:21)
    at /home/runner/work/Prompty/Prompty/web_next/node_modules/vite-plugin-top-level-await/dist/bundle-info.js:33:19
    at Array.map (<anonymous>)
    at parseBundleAsts (/home/runner/work/Prompty/Prompty/web_next/node_modules/vite-plugin-top-level-await/dist/bundle-info.js:31:78)
    at Object.generateBundle (/home/runner/work/Prompty/Prompty/web_next/node_modules/vite-plugin-top-level-await/dist/index.js:93:72)
    at file:///home/runner/work/Prompty/Prompty/web_next/node_modules/rollup/dist/es/shared/node-entry.js:18692:40
Error: Process completed with exit code 1.
```

This is my package.json dependencies:
```json
"dependencies": {
        "@nextui-org/react": "^2.2.9",
        "@tanstack/react-query": "^5.18.0",
        "@types/stats.js": "^0.17.3",
        "@types/three": "^0.161.2",
        "firebase": "^10.7.2",
        "framer-motion": "^10.18.0",
        "localforage": "^1.10.0",
        "match-sorter": "^6.3.3",
        "react": "^18.2.0",
        "react-dom": "^18.2.0",
        "react-router-dom": "^6.21.3",
        "stats.js": "^0.17.0",
        "three": "^0.161.0",
        "usehooks-ts": "^2.10.0"
    },
    "devDependencies": {
        "@tanstack/eslint-plugin-query": "^5.18.0",
        "@types/node": "^20.11.10",
        "@types/react": "^18.2.43",
        "@types/react-dom": "^18.2.17",
        "@types/uuid": "^9.0.8",
        "@typescript-eslint/eslint-plugin": "^6.14.0",
        "@typescript-eslint/parser": "^6.14.0",
        "@vitejs/plugin-react": "^4.2.1",
        "@vitejs/plugin-react-swc": "^3.5.0",
        "autoprefixer": "^10.4.17",
        "eslint": "^8.55.0",
        "eslint-config-prettier": "^9.0.0",
        "eslint-import-resolver-typescript": "^3.6.1",
        "eslint-plugin-import": "^2.28.1",
        "eslint-plugin-jsx-a11y": "^6.7.1",
        "eslint-plugin-react": "^7.33.2",
        "eslint-plugin-react-hooks": "^4.6.0",
        "eslint-plugin-react-refresh": "^0.4.5",
        "npm-run-all": "^4.1.5",
        "postcss": "^8.4.33",
        "tailwindcss": "^3.4.1",
        "typescript": "^5.2.2",
        "vite": "^5.0.8",
        "vite-plugin-checker": "^0.6.4",
        "vite-plugin-svgr": "^4.2.0",
        "vite-plugin-top-level-await": "^1.4.1",
        "vite-plugin-wasm": "^3.3.0"
    },
    "optionalDependencies": {
        "@rollup/rollup-linux-x64-gnu": "4.9.6"
    }
```

This is my github action:
```
name: Deploy to Firebase Hosting on merge
"on":
    push:
        branches:
            - main
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true
                  target: wasm32-unknown-unknown
            - uses: Swatinem/rust-cache@v2
            - run: npm install -g wasm-pack
            - run: |
                  cd web_next
                  npm install
                  npm run build
            - uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: "${{ secrets.GITHUB_TOKEN }}"
                  firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROMPTY_58A21 }}"
                  channelId: live
                  projectId: prompty-58a21
```
